version: 2.1

slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/notify:
        custom: |
          {
            "text": "",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "❌ *Failure* in Build:`#${CIRCLE_BUILD_NUM}` Project:`${CIRCLE_PROJECT_REPONAME}` on Branch:`${CIRCLE_BRANCH}`"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${CIRCLE_BUILD_URL}"
                  }
                ]
              }
            ]
          }
        event: fail

orbs:
  slack: circleci/slack@4.3.3

commands:
  revert-migration:
    description: Revert to previous Docker image
    steps:
      - run:
          name: Revert migration
          when: on_fail
          command: |
            export revert_dh_image=$(curl -H "token: ${MEMSTASH_TOKEN}" --request GET https://api.memstash.io/values/revert_${CIRCLE_WORKFLOW_ID:0:7})
            kubectl delete deployment udacity-duckhunt --wait
            kubectl create deployment udacity-duckhunt --image=$revert_dh_image
            (kubectl get services | grep duckhunt -q) || kubectl expose deployment udacity-duckhunt --port=80 --target-port=8080 --name=duckhunt --type=LoadBalancer

  aws-cli-install-circleci-node:
    description: Install the AWS-CLI Tools In CircleCI-Node image
    steps:
      - run:
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "$HOME/awscliv2.zip"
            cd $HOME && unzip awscliv2.zip
            cd $HOME/aws && sudo ./install

jobs:
  lint:
    # working_directory: ~/project.home
    docker: 
      - image: circleci/node:14.17.3
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y curl jq zip unzip
            ./hadolint --version || (curl -Lo hadolint https://github.com/hadolint/hadolint/releases/download/v2.5.0/hadolint-linux-x86_64 && chmod +x hadolint && sudo mv hadolint /usr/local/bin)
      - checkout
          # path: ~/project.home
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  build:
    # working_directory: ~/project.home
    machine: true
    steps:
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - checkout
          # path: ~/project.home
      - run:
          name: Docker Build
          command: |
            docker build -t $DOCKER_USER/$DOCKER_IMAGE_NAME.${CIRCLE_WORKFLOW_ID:0:7} .
      - run:
          name: Docker Push
          command: |
            docker push $DOCKER_USER/$DOCKER_IMAGE_NAME.${CIRCLE_WORKFLOW_ID:0:7}
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  pre-deploy:
    # working_directory: ~/project.home
    docker: 
      - image: circleci/node:14.17.3
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y curl jq zip unzip
            curl -Lo kops https://github.com/kubernetes/kops/releases/download/v1.19.2/kops-linux-amd64
            chmod +x ./kops && sudo mv kops /usr/local/bin
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl && sudo mv kubectl /usr/local/bin
      - aws-cli-install-circleci-node
      - checkout
          # path: ~/project.home
      - run:
          name: Export KOPS KUBECONFIG
          command: |
            export KOPS_CLUSTER_NAME=$(cat ansible/vars/main.yml| grep cluster_name: | awk '{print $2}' | sed 's/"//g')
            export KOPS_STATE_STORE=$(cat ansible/vars/main.yml| grep KOPS_STATE_STORE: | awk '{print $2}' | sed 's/"//g')
            export AWS_DEFAULT_REGION=$(cat ansible/vars/main.yml| grep aws_region: | awk '{print $2}' | sed 's/"//g')
            echo "KOPS Cluster Name: $KOPS_CLUSTER_NAME"
            echo "KOPS State Store : $KOPS_STATE_STORE"
            aws s3 ls
            kops export kubecfg --admin --name $KOPS_CLUSTER_NAME
      - run:
          name: Store currently deployed image 
          command: |
            export revert_dh_image=$(kubectl describe deployment udacity-duckhunt | grep Image: | awk {'print $2'})
            curl -H "Content-Type: text/plain" -H "token: ${MEMSTASH_TOKEN}" --request PUT --data "$revert_dh_image" https://api.memstash.io/values/revert_${CIRCLE_WORKFLOW_ID:0:7}
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  deploy:
    # working_directory: ~/project.home
    docker:
      - image: circleci/node:14.17.3
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y curl jq zip unzip
            curl -Lo kops https://github.com/kubernetes/kops/releases/download/v1.19.2/kops-linux-amd64
            chmod +x ./kops && sudo mv kops /usr/local/bin
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl && sudo mv kubectl /usr/local/bin
      - aws-cli-install-circleci-node
      - checkout
          # path: ~/project.home
      - run:
          name: Export KOPS KUBECONFIG
          command: |
            export KOPS_CLUSTER_NAME=$(cat ansible/vars/main.yml| grep cluster_name: | awk '{print $2}' | sed 's/"//g')
            export KOPS_STATE_STORE=$(cat ansible/vars/main.yml| grep KOPS_STATE_STORE: | awk '{print $2}' | sed 's/"//g')
            export AWS_DEFAULT_REGION=$(cat ansible/vars/main.yml| grep aws_region: | awk '{print $2}' | sed 's/"//g')
            echo "KOPS Cluster Name: $KOPS_CLUSTER_NAME"
            echo "KOPS State Store : $KOPS_STATE_STORE"
            kops export kubecfg --admin --name $KOPS_CLUSTER_NAME
      - run:
          name: Deploy Newer Duckhunt Docker Image 
          command: |
            kubectl delete deployment udacity-duckhunt --wait
            kubectl create deployment udacity-duckhunt --image=$DOCKER_USER/$DOCKER_IMAGE_NAME.${CIRCLE_WORKFLOW_ID:0:7}
            (kubectl get services | grep duckhunt -q) || kubectl expose deployment udacity-duckhunt --port=80 --target-port=8080 --name=duckhunt --type=LoadBalancer
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  test:
    # working_directory: ~/project.home
    docker:
      - image: circleci/node:14.17.3
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y curl jq zip unzip python3-pip
            sudo pip3 install ansible==4.2.0
            curl -Lo kops https://github.com/kubernetes/kops/releases/download/v1.19.2/kops-linux-amd64
            chmod +x ./kops && sudo mv kops /usr/local/bin
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl && sudo mv kubectl /usr/local/bin
      - aws-cli-install-circleci-node
      - checkout
          # path: ~/project.home
      - run:
          name: Export KOPS KUBECONFIG
          command: |
            export KOPS_CLUSTER_NAME=$(cat ansible/vars/main.yml| grep cluster_name: | awk '{print $2}' | sed 's/"//g')
            export KOPS_STATE_STORE=$(cat ansible/vars/main.yml| grep KOPS_STATE_STORE: | awk '{print $2}' | sed 's/"//g')
            export AWS_DEFAULT_REGION=$(cat ansible/vars/main.yml| grep aws_region: | awk '{print $2}' | sed 's/"//g')
            echo "KOPS Cluster Name: $KOPS_CLUSTER_NAME"
            echo "KOPS State Store : $KOPS_STATE_STORE"
            kops export kubecfg --admin --name $KOPS_CLUSTER_NAME
      - run:
          name: Test Duckhunt Web
          command: ansible-playbook ansible/elbtest.yml
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          custom: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *Success* -- Configure desired CNAME record to point to $DUCKHUNT_ELB"
                  }
                }
              ]
            }
      - revert-migration

  last-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Success
          command: |
            exit 0

workflows:
  default:
    jobs:
      - lint:
          context:
            - Slack
          <<: *slack-fail-post-step
      - build:
          requires: [lint]
          context:
            - Slack
            - Docker_DH
          <<: *slack-fail-post-step
      - pre-deploy:
          requires: [build]
          context:
            - Slack
            - Docker_DH
            - AWSCLI
          <<: *slack-fail-post-step
      - deploy:
          requires: [pre-deploy]
          context:
            - Slack
            - Docker_DH
            - AWSCLI
          <<: *slack-fail-post-step
      - test:
          requires: [deploy]
          context:
            - Slack
            - Docker_DH
            - AWSCLI
          <<: *slack-fail-post-step
      - last-job:
          context:
            - Slack
          requires:
            - lint
            - build
            - pre-deploy
            - deploy
            - test
          post-steps:
            - slack/notify:
                custom: |
                  {
                    "text": "",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "✅ *Success* Build:`#${CIRCLE_BUILD_NUM}` Project:`${CIRCLE_PROJECT_REPONAME}` on Branch:`${CIRCLE_BRANCH}`"
                        }
                      },
                      {
                        "type": "actions",
                        "elements": [
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "View Job"
                            },
                            "url": "${CIRCLE_BUILD_URL}"
                          }
                        ]
                      }
                    ]
                  }
                event: always