---
  - name: Testing
    hosts: localhost
    connection: localhost
    vars:
#      s3_whitelist: "s3://cluster.fuelsman.io/whitelist.csv"
      cluster_spec_file: "/tmp/duckhunt.clusterspec.yml"
#      cidr_list: []
    vars_files:
      - vars/main.yml
    tasks:
    - debug: 
        msg: "{{ ansible_system|lower }}"
    # - name: Download Cluster Whitelist CSV File
    #   shell: "aws s3 cp {{ s3_whitelist }} ."
    # - name: Read Cluster Whitelist CSV File
    #   read_csv:
    #     path: ./whitelist.csv
    #   register: ip_whitelist
    # - name: get list
    #   set_fact:
    #     cidr_list: '{{ cidr_list + [item.cidr]}}'
    #   loop: "{{ip_whitelist.list}}"
    # - include_role: 
    #     name: create-cluster-spec
    # - name: Insert cidr list for kubernetes access
    #   replace:
    #     regexp: "kubernetesApiAccess:"
    #     path: "{{cluster_spec_file}}"
    #     replace: "kubernetesApiAccess: {{cidr_list}}"
    #   tags:
    #   - deploy
    # - name: Insert cidr list for ssh access
    #   replace:
    #     regexp: "sshAccess:"
    #     path: "{{cluster_spec_file}}"
    #     replace: "sshAccess: {{cidr_list}}"
    #   tags:
    #   - deploy